All wrapper scripts customized. Output and new options.

diff --git a/lpc3131/examples/gnublin-adcmod/gnublin-adcmod b/lpc3131/examples/gnublin-adcmod/gnublin-adcmod
--- a/lpc3131/examples/gnublin-adcmod/gnublin-adcmod
+++ b/lpc3131/examples/gnublin-adcmod/gnublin-adcmod
@@ -15,16 +15,26 @@ error=""
 i2cbus="1"
 address="0x48"
 json_f="0"
-helpstring='This Script prints out the value of a selected adc-channel from the gnublin-adc-module 
+brute_f="0"
+init_f="0"
+rm_f="0"
+helpstring='This Script prints out the value of a selected adc-channel of the gnublin-adc-module 
 
--h			Show this help
--j			Convert output to json format
--c			Select ADC Channel (0 - 7 possible, default is 0)
--a			I2C-Address of the module (default is 0x48)
+-h Show this help
+-b show raw output
+-j Convert output to json format
+-i just initialize the adc module with given address (default is 0x48)
+-r just remove the adc driver.
+-c Select ADC Channel (0 - 7 possible, default is 0)
+-a I2C-Address of the module (default is 0x48)
 
 Example:
 
-gnublin-adcmod -j -a 0x48 -c 2  <- channel=2, I2C-Address=0x48 print value in json format.'
+channel=2, I2C-Address=0x48 print value in json format:
+gnublin-adcmod -j -a 0x48 -c 2  
+
+channel=7, I2C-Address=0x4A print value in normal format:
+gnublin-adcmod -a 0x4A -c 7'
 
 
 check_channel() {
@@ -33,7 +43,7 @@ check_channel() {
 
 			if [ "$json_f" == "1" ]
 			then
-			    echo "{ \"error_msg\" : \"channel is not valid \",\"result\" : \"-1\" }"
+			    echo "{ \"error_msg\" : \"channel is not valid\",\"result\" : \"-1\" }"
 			else
 			echo "channel is not valid"
 			fi
@@ -42,22 +52,19 @@ check_channel() {
 }
 
 
-#module autoload
-lsmod | grep "ads7828"  >/dev/null
-if [ "$?" == "1" ]
-then
-	modprobe ads7828 >/dev/null
-	sleep 2
-fi 
+
 
 #parse the parameters
-while getopts c:a:jh opt
+while getopts c:a:jhbir opt
  do
       case $opt in
           c) channel="${OPTARG}" ;;
 
 	  a) address="${OPTARG}" ;;
           j) json_f="1" ;;
+	  b) brute_f="1" ;;
+	  i) init_f="1" ;;
+	  r) rm_f="1" ;;
           ?) echo "$helpstring"
              exit 1 ;;
 	  h) echo "$helpstring"
@@ -65,22 +72,56 @@ while getopts c:a:jh opt
       esac
 done
 
+    if [ $rm_f == "1" ]
+    then
+	modprobe -r ads7828 >/dev/null
+	exit 1
+    fi 
+
+
 #check if adress is a hex-value
 if [  "${address:0:2}" != "0x" ]
 then
     result="I2C-address is not a hex-value."
     if [ "$json_f" == "1" ]
     then
-        echo "{ \"error_msg\" : \"$result \",\"result\" : \"-2\" }"
+        echo "{ \"error_msg\" : \"$result\",\"result\" : \"-2\" }"
     else
         echo $result
     fi
     exit 1
 fi
 
+
+#module autoload
+lsmod | grep "ads7828"  >/dev/null
+if [ "$?" == "1" ]
+then
+
+    if [ $init_f == "1" ]
+    then
+	modprobe ads7828 >/dev/null
+	exit 1
+    else
+	modprobe ads7828 >/dev/null
+	sleep 1
+    fi 
+fi
+
 #check for parameter problems
 check_channel $channel
 
+#check if channel_value is an integer
+if [ "${channel//[0-9]*}" != "" ] 
+then
+		if [ "$json_f" == "1" ]
+		then
+			echo "{ \"error_msg\" : \"Only Integers allowed for channel\",\"result\" : \"-3\" }"
+		else
+		echo "Only Integers allowed for channel"
+		fi
+   exit 1
+fi
 
 #read the value
 if [ -f /sys/module/ads7828/drivers/i2c:ads7828/${i2cbus}-00${address:2}/in${channel}_input ]
@@ -91,17 +132,17 @@ result=$(cat "/sys/module/ads7828/drivers/i2c:ads7828/${i2cbus}-00${address:2}/i
 	#print result in normal format or in json format
 	if [ "$json_f" == "1" ]
 	then
-	    echo "{ \"voltage\" : \"$result \",\"result\" : \"0\" }"
+	    echo "{ \"voltage\" : \"$result\",\"result\" : \"0\" }"
 	else
     echo $result
 	fi 
 else 
 
 	#print result in normal format or in json format
-	error="File not found. Please use the correct I2C-address or connect the adc-module.YOu can also try to load/reload the module ads7828"
+	error="File not found. Please use the correct I2C-address or connect the adc-module.You can also try to load/reload the module ads7828"
 	if [ "$json_f" == "1" ]
 	then
-	    echo "{ \"error_msg\" : \"$error \",\"result\" : \"-3\" }"
+	    echo "{ \"error_msg\" : \"$error\",\"result\" : \"-4\" }"
 	else
 	    echo $error
 	fi 
diff --git a/lpc3131/examples/gnublin-gpio/gnublin-gpio b/lpc3131/examples/gnublin-gpio/gnublin-gpio
--- a/lpc3131/examples/gnublin-gpio/gnublin-gpio
+++ b/lpc3131/examples/gnublin-gpio/gnublin-gpio
@@ -16,17 +16,23 @@ freef=""
 output_val=""
 json_f=""
 helpstring='This script grants access to the GNUBLIN gpio pins.It also works with pca9555 portexpander. 
--h			Show this help
--j			Convert output to json format
--p <value>		Select gpio Pin (default=14) <value> between 1 and 20
--i			configure pin as input
--o <value>		configure pin as output and set a value 1=high,0=low
--f 			free the gpio Pin
+-h Show this help
+-j Convert output to json format
+-p <value> Select gpio Pin (default=14) <value> between 1 and 20
+-i configure pin as input
+-o <value> configure pin as output and set a value 1=high,0=low
+-f free the gpio Pin
 
 Example:
-gnublin-gpio -i -p 14 -j    <- set GPIO14 Pin as input, read value and print it in json format.
-gnublin-gpio -o 1 -p 11     <- set GPIO11 Pin as output with a high value
-gnublin-gpio -o 0 -p 11     <- set GPIO11 Pin as output with a low value'
+
+set GPIO14 Pin as input, read value and print it in json format:
+gnublin-gpio -i -p 14 -j
+
+set GPIO11 Pin as output with a high value:
+gnublin-gpio -o 1 -p 11     
+
+set GPIO11 Pin as output with a low value:
+gnublin-gpio -o 0 -p 11 '
 
 
 
@@ -73,7 +79,17 @@ then
 fi 
 
 
-
+#check if pin is an integer
+if [ "${pin//[0-9]*}" != "" ] 
+then
+		if [ "$json_f" == "1" ]
+		then
+			echo "{ \"error_msg\" : \"Only Integers allowed for pin\",\"result\" : \"-5\" }"
+		else
+		echo "Only Integers allowed for pin"
+		fi
+   exit 1
+fi
 
 #first make sure that gpio pin is exported in sysfs
 if [ ! -d "/sys/class/gpio/gpio${pin}" ]
diff --git a/lpc3131/gnublin_package/src/gnublin-adcint/usr/bin/gnublin-adcint b/lpc3131/gnublin_package/src/gnublin-adcint/usr/bin/gnublin-adcint
--- a/lpc3131/gnublin_package/src/gnublin-adcint/usr/bin/gnublin-adcint
+++ b/lpc3131/gnublin_package/src/gnublin-adcint/usr/bin/gnublin-adcint
@@ -12,18 +12,24 @@
 channel="1"
 result=""
 json_f="0"
+brute_f="0"
 devfile="/dev/lpc313x_adc"
 string='
 Module automaticly loaded'
 helpstring='This Script prints out the values of a selected internal adc channel 
--h			Show this help
--j			Convert output to json format
--c			Select gpa<x> Pin (1 is default)
--d			Choose Path to device file
+-h Show this help
+-b show raw output
+-j Convert output to json format
+-c Select gpa<x> Pin (1 is default)
+-d Choose Path to device file
 
 Example:
 
-gnublin-adcint -j -c 3   <- read value of channel 2 and print it in json format'
+read value of channel 3 and print it in json format:
+gnublin-adcint -j -c 3
+
+read value of channel 1 and print it in normal format:
+gnublin-adcint -c 1'
 
 
 check_channel() {
@@ -38,16 +44,6 @@ check_channel() {
 		echo "channel is not valid"
 		fi
 		exit 1
-	elif [ "$1" = "2" ] 
-        then
-		
-		if [ "$json_f" == "1" ]
-		then
-			echo "{ \"error_msg\" : \"channel is not valid \",\"result\" : \"-1\" }"
-		else
-		echo "channel is not valid"
-		fi
-		exit 1
 	fi 
 }
 
@@ -57,28 +53,44 @@ if [ "$#" = "0" ]
 then 
 		if [ "$json_f" == "1" ]
 		then
-			echo "{ \"error_msg\" : \"No parameters given. -h for help \",\"result\" : \"-2\" }"
+			echo "{ \"error_msg\" : \"No parameters given. -h for help\",\"result\" : \"-2\" }"
 		else
 		echo "No parameters given. -h for help"
 		fi
    exit 1
 fi 
 
+
+#check if channel_value is an integer
+if [ "${channel//[0-9]*}" != "" ] 
+then
+		if [ "$json_f" == "1" ]
+		then
+			echo "{ \"error_msg\" : \"Only Integers allowed for channel\",\"result\" : \"-3\" }"
+		else
+		echo "Only Integers allowed for channel"
+		fi
+   exit 1
+fi
+
+
+
 #modul autoload
 lsmod | grep "lpc313x_adc"  >/dev/null
 if [ "$?" == "1" ]
 then
 	modprobe lpc313x_adc
-	sleep 2
+	sleep 1
 fi 
 
 #parse parameters
-while getopts c:d:jh opt
+while getopts c:d:jhb opt
  do
       case $opt in
           c) channel="${OPTARG}" ;;
           d) devfile="${OPTARG}" ;;
           j) json_f="1" ;;
+          b) brute_f="1" ;;
           ?) echo "$helpstring"
              exit 1 ;;
 		  h) echo "$helpstring"
@@ -95,7 +107,7 @@ then
 	
 		if [ "$json_f" == "1" ]
 		then
-		echo "{ \"error_msg\" : \"File: $devfile was not found \",\"result\" : \"-2\" }"
+		echo "{ \"error_msg\" : \"File: $devfile was not found\",\"result\" : \"-4\" }"
 		else
 		echo "File: $devfile was not found"
 		fi
@@ -112,7 +124,9 @@ let result="${tmp}"
 #print the result in normal format or in json format
 if [ "$json_f" == "1" ]
 then
-    echo "{ \"voltage\" : \" $result\",\"result\" : \"0\" }"
+    echo "{ \"voltage\" : \"$result\",\"result\" : \"0\" }"
+elif [ "$brute_f" == "1"  ] 
+    echo $result
 else
     echo $result
 fi 
diff --git a/lpc3131/gnublin_package/src/gnublin-pwm/usr/bin/gnublin-pwm b/lpc3131/gnublin_package/src/gnublin-pwm/usr/bin/gnublin-pwm
--- a/lpc3131/gnublin_package/src/gnublin-pwm/usr/bin/gnublin-pwm
+++ b/lpc3131/gnublin_package/src/gnublin-pwm/usr/bin/gnublin-pwm
@@ -16,13 +16,18 @@ json_f="0"
 devfile="/dev/lpc313x_pwm"
 helpstring='This wrapper Script controls the pwm interface of GNUBLIN 
 
--h			Show this help
--j			print output in json format.
--d			Choose Path to device file.
--v 			Hex-value for pwm duty cycle in. <high-byte><low-byte>
+-h Show this help
+-j print output in json format.
+-d Choose Path to device file.
+-v Hex-value for pwm duty cycle in. <high-byte><low-byte>
 
 Example:
-gnublin-pwm -v ff     <- this command starts the pwm interface with specified value.'
+
+this command starts the pwm interface with specified value.
+gnublin-pwm -v 0xff
+
+this command starts the pwm interface with specified value.
+gnublin-pwm -v 0xff'
 
 
 
@@ -51,13 +56,27 @@ while getopts d:v:hj opt
       esac
 done
 
+#check if value is a hex-value
+if [  "${value:0:2}" != "0x" ]
+then
+    result="Value is not a hex-value."
+    if [ "$json_f" == "1" ]
+    then
+        echo "{ \"error_msg\" : \"$result\",\"result\" : \"-1\" }"
+    else
+        echo $result
+    fi
+    exit 1
+fi
+
+
 #modul autoload
 lsmod | grep "lpc313x_pwm"  >/dev/null
 
 if [ "$?" == "1" ]
 then
 	modprobe lpc313x_pwm
-        sleep 2
+        sleep 1
 fi 
 
 
@@ -89,14 +108,14 @@ fi
 
 
 
-echo $value | grep -E "[^0-9a-fA-F]"
+echo "${value:2:2}" | grep -E "[^0-9a-fA-F]"
 if [ "$?" == "0" ]; 
 then
 	if [ "$json_f" == "1" ]
 	then
-	    echo "{ \"error_msg\" : \"Value must be between 00 and ff\",\"result\" : \"-4\" }"
+	    echo "{ \"error_msg\" : \"Value must be between 0x00 and 0xff\",\"result\" : \"-4\" }"
 	else
-        echo "Value must be between 00 and ff."
+        echo "Value must be between 0x00 and 0xff."
 	fi
     exit 1
 fi
